/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

//$(NDK_ROOT)\platforms\android - 24\arch - arm\usr\include
/* Header for class com_jni_netutil_CJniUtil */

#ifndef _Included_com_jni_netutil_CJniUtil
#define _Included_com_jni_netutil_CJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    StartClient
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_StartClient
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    StopClient
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_netutil_CJniUtil_StopClient
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetToken
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_netutil_CJniUtil_GetToken
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetTokenlen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetTokenlen
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsConnectAuth
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_IsConnectAuth
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsConnectLobby
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_IsConnectLobby
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsConnectRoom
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_IsConnectRoom
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsTokenLoginLobby
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_IsTokenLoginLobby
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsTokenLoginRoom
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_IsTokenLoginRoom
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ConnectAuth
 * Signature: (Ljava/lang/String;SI)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ConnectAuth
  (JNIEnv *, jobject, jstring, jshort, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DisConnectAuth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DisConnectAuth
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ConnectLobby
 * Signature: (Ljava/lang/String;SI)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ConnectLobby
  (JNIEnv *, jobject, jstring, jshort, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DisConnectLobby
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DisConnectLobby
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ConnectRoom
 * Signature: (Ljava/lang/String;SII)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ConnectRoom
  (JNIEnv *, jobject, jstring, jshort, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DisConnectRoom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DisConnectRoom
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IdPassAuth
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_IdPassAuth
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    TouristAuth
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_TouristAuth
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ConfirmToken
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ConfirmToken
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    EnterRoom
 * Signature: (IILjava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_EnterRoom
  (JNIEnv *, jobject, jint, jint, jstring, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomAllInfomation
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomAllInfomation
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetWaitMicList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetWaitMicList
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomWaitMic
 * Signature: (ISCLjava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomWaitMic
  (JNIEnv *, jobject, jint, jshort, jchar, jstring, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomCancleWaitMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomCancleWaitMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomUpWaitMic
 * Signature: (CIC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomUpWaitMic
  (JNIEnv *, jobject, jchar, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomDownWaitMic
 * Signature: (CIC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomDownWaitMic
  (JNIEnv *, jobject, jchar, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomKickSomeOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomKickSomeOne
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomForbidenSomeOne
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomForbidenSomeOne
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomOnvjMic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomOnvjMic
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomOffvjMic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomOffvjMic
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomGivOnevjMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomGivOnevjMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ApplyGetVJmic
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ApplyGetVJmic
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomGiveOffvjMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomGiveOffvjMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomGiveOffMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomGiveOffMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomUpdateBlackList
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomUpdateBlackList
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomUpdateMgrList
 * Signature: (ICC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomUpdateMgrList
  (JNIEnv *, jobject, jint, jchar, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    LoginLobby
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_LoginLobby
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    LoginLobbyAuto
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_LoginLobbyAuto
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserInfo_AII
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetUserInfo_1AII
  (JNIEnv *, jobject, jintArray, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetFriendListWithoutUserInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetFriendListWithoutUserInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetBlackListWithoutUserInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetBlackListWithoutUserInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    AddFriend
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_AddFriend
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    AddBlack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_AddBlack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DelFriend
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DelFriend
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DelBlack
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DelBlack
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetChannellist
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetChannellist
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomListEx
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomListEx
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomInfo
 * Signature: (II[I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomInfo
  (JNIEnv *, jobject, jint, jint, jintArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetTmpRoomInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetTmpRoomInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    CreateAvatar
 * Signature: (Ljava/lang/String;Lcom/jni/netutil/ResultData_Avatar_Updata;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_CreateAvatar
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ChangeAvatar
 * Signature: (Lcom/jni/netutil/ResultData_Avatar_Updata;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ChangeAvatar
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ChangeNickName
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ChangeNickName
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendFlower
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendFlower
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    BroadAll
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_BroadAll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    BroadLobby
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_BroadLobby
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendRoomNotice
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendRoomNotice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetLobbyInfo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetLobbyInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    InviteMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_InviteMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendChatToUser
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendChatToUser
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendChatToClub
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendChatToClub
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendChatToRoom
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendChatToRoom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendSpeakerToAll
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendSpeakerToAll
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendSpeakerToLobby
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendSpeakerToLobby
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    QueryFriendLocation
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_QueryFriendLocation
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomApplyList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomApplyList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ApplyRoomMember
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ApplyRoomMember
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    AuditAddApply
 * Signature: (IIC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_AuditAddApply
  (JNIEnv *, jobject, jint, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomMemberList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomMemberList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    UnchainMember
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_UnchainMember
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomPesideAssistant
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomPesideAssistant
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomPeside
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomPeside
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomSubHost
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomSubHost
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomMember
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomMember
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetBlackList
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetBlackList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    AddDelBlack
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_AddDelBlack
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomPanelInfo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomPanelInfo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomPassword
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomPassword
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomSwitch
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomSwitch
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomPrivate
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomPrivate
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetUserInOutSwitch
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetUserInOutSwitch
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetGetMicSwitch
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetGetMicSwitch
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetOnMicSwitch
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetOnMicSwitch
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ModifyRoomName
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ModifyRoomName
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomAffiche
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomAffiche
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    AllowRoomAllChat
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_AllowRoomAllChat
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomSalutatory
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomSalutatory
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetRoomLogo
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetRoomLogo
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetPartInfo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetPartInfo
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomList_II
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomList_1II
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    LeaveRoom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_LeaveRoom
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ApplyAddFriend
 * Signature: (IC)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ApplyAddFriend
  (JNIEnv *, jobject, jint, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomSimpleInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomSimpleInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomSimpleInfoEx
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomSimpleInfoEx
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ExitRoomMember
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ExitRoomMember
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetLobbyOnlineNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetLobbyOnlineNum
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    BuyPack
 * Signature: ([Lcom/jni/netutil/ResultData_Buy;III)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_BuyPack
  (JNIEnv *, jobject, jobjectArray, jint, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetPack
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetPack
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    DelPack
 * Signature: (I[II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_DelPack
  (JNIEnv *, jobject, jint, jintArray, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    UsePack
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_UsePack
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    CreateRoom
 * Signature: (Lcom/jni/netutil/ResultData_CreateRoom;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_CreateRoom
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendFireworks
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendFireworks
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGiftTopList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetGiftTopList
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetOnlineTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetOnlineTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetNewUserTask
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetNewUserTask
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    TaskStep
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_TaskStep
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    TaskGift
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_TaskGift
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGiftInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetGiftInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetSystemBroad
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetSystemBroad
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserSeel
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetUserSeel
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendSysteInfo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendSysteInfo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGroupInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetGroupInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomListInGroup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomListInGroup
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomListInGroupBatch
 * Signature: ([S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomListInGroupBatch
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetSongInfoList
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetSongInfoList
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetAvServerList
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetAvServerList
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetOffLineMsg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetOffLineMsg
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomSortInGroup
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomSortInGroup
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserSpeakerInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetUserSpeakerInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetFamilyInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetFamilyInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RoomScore
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RoomScore
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ShowRoomIncome
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ShowRoomIncome
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ShowRoomGetIncome
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ShowRoomGetIncome
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomIncome
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetRoomIncome
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendPcData
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendPcData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    InviteJoinRoom
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_InviteJoinRoom
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ReInviteJoinRoom
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ReInviteJoinRoom
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGiftSend
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetGiftSend
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGiftRecv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetGiftRecv
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    KickUserByMac
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_KickUserByMac
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    KickUserByIp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_KickUserByIp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SetOnMicTemainTime
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SetOnMicTemainTime
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendSongRemnantsTime
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendSongRemnantsTime
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    OpenPrivateMic
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_OpenPrivateMic
  (JNIEnv *, jobject, jshort);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ClosePrivateMic
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ClosePrivateMic
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ClosedPrivateMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ClosedPrivateMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestWatchPrivateMic
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestWatchPrivateMic
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ResponseWatchPrivateMic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ResponseWatchPrivateMic
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    InviteWatchPrivateMic
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_InviteWatchPrivateMic
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ResponseInviteWatchPrivateMic
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ResponseInviteWatchPrivateMic
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    OpenRoomPrivateMicFlag
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_OpenRoomPrivateMicFlag
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    CrownKickoutSomeOne
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_CrownKickoutSomeOne
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    ForbidUserIp
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_ForbidUserIp
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SingerScores
 * Signature: (I[S)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SingerScores
  (JNIEnv *, jobject, jint, jshortArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    UpdateSong
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_UpdateSong
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserInfoForSpeaker
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetUserInfoForSpeaker
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserInfoWithVersion
 * Signature: ([Lcom/jni/netutil/RequestData_IdxWithVersion;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetUserInfoWithVersion
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    InitDownLoadUrl
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_InitDownLoadUrl
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    InitLocalDatabaseDir
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_InitLocalDatabaseDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetMyInfo
 * Signature: ()Lcom/jni/netutil/LocalData_UserInfo;
 */
JNIEXPORT jobject JNICALL Java_com_jni_netutil_CJniUtil_GetMyInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetSelfData
 * Signature: ()Lcom/jni/netutil/ResultData_SelfData;
 */
JNIEXPORT jobject JNICALL Java_com_jni_netutil_CJniUtil_GetSelfData
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetMyIdx
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_GetMyIdx
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    IsWangtong
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_IsWangtong
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetRoomInfoFromLocal
 * Signature: (I)Lcom/jni/netutil/ResultData_RoomInfo;
 */
JNIEXPORT jobject JNICALL Java_com_jni_netutil_CJniUtil_GetRoomInfoFromLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetUserInfoFromLocal
 * Signature: (I)Lcom/jni/netutil/LocalData_UserInfo;
 */
JNIEXPORT jobject JNICALL Java_com_jni_netutil_CJniUtil_GetUserInfoFromLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetGiftInfoFromLocal
 * Signature: (I)Lcom/jni/netutil/GiftInfo;
 */
JNIEXPORT jobject JNICALL Java_com_jni_netutil_CJniUtil_GetGiftInfoFromLocal
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    GetAllGiftId
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_jni_netutil_CJniUtil_GetAllGiftId
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendChatKTV
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendChatKTV
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    SendGiftInLobby
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_SendGiftInLobby
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    MFInitFilter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_MFInitFilter
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    MFFilter
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_netutil_CJniUtil_MFFilter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    MFFindSensWord
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_MFFindSensWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    MFFindSensWord2
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_jni_netutil_CJniUtil_MFFindSensWord2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestSendHB
 * Signature: (BIILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestSendHB
  (JNIEnv *, jobject, jbyte, jint, jint, jstring, jint);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestHBStatus
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestHBStatus
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestVieHB
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestVieHB
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestHBDetail
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestHBDetail
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_netutil_CJniUtil
 * Method:    RequestCurrentRoomHB
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jni_netutil_CJniUtil_RequestCurrentRoomHB
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
