package com.jni.netutil;


public interface JniMessage {
	int AUTH_NORMAL=1000;				//正常
	int AUTH_NOTEXIST=AUTH_NORMAL+1;					//帐号不存在
	int AUTH_PWDERROR=AUTH_NORMAL+2;					//登陆密码不存在
	int AUTH_TOURISTERROR=AUTH_NORMAL+3;				//游客登录失败
	int AUTH_CACHEERROR=AUTH_NORMAL+4;				//登录不成功
	int AUTH_TOKENERROR=AUTH_NORMAL+5;				//取得token失败
	int AUTH_MAX=AUTH_NORMAL+999;

	int LOBBY_NORMAL=2000;				//正常
	int LOBBY_NONEED_UPDATE = LOBBY_NORMAL+1;        //用户信息无需更新，可以从本地数据库获取
	int LOBBY_LOGIN_IDLOCK=LOBBY_NORMAL+2;				//账号被冻结
	int LOBBY_LOGIN_TOOOLD=LOBBY_NORMAL+3;				//版本错误
	int LOBBY_LOGIN_NOTEXIST=LOBBY_NORMAL+4;			//用户不存在
	int LOBBY_LOGIN_NOAVATAR=LOBBY_NORMAL+5;			//还未创建avatar信息
	int LOBBY_USERINFO_NOTEXIST=LOBBY_NORMAL+6;		//用户信息不存在
	int LOBBY_USERINFO_INDULGE=LOBBY_NORMAL+7;			//用户防沉迷
/***添加/删除 好友、黑名单错误代码***/
	int LOBBY_ADDFRIEND_NORMAL=LOBBY_NORMAL+8;			//正常
	int LOBBY_ADDFRIEND_WAIT=LOBBY_NORMAL+9;			//已转发;等待对方回复。
	int LOBBY_ADDFRIEND_INPROCESS=LOBBY_NORMAL+10;		//正处理状态
	int LOBBY_ADDFRIEND_REPEAT=LOBBY_NORMAL+11;			//服务器拒绝状态(重复添加)
	int LOBBY_ADDFRIEND_FRIEND=LOBBY_NORMAL+12;			//已是好友
	int LOBBY_ADDFRIEND_REFUSE=LOBBY_NORMAL+13;			//用户拒绝
	int LOBBY_ADDFRIEND_OFFLINE=LOBBY_NORMAL+14;		//用户不在线
	int LOBBY_ADDFRIEND_DBERROR=LOBBY_NORMAL+15;		//数据库返回失败
	int LOBBY_ADDFRIEND_ADDSELF=LOBBY_NORMAL+16;		//不能添加自己为好友
	int LOBBY_ADDFRIEND_ALREADY=LOBBY_NORMAL+17;		//已经添加对方为好友
	int LOBBY_ADDFRIEND_NOTEXIST=LOBBY_NORMAL+18;		//自己的idx或对方有idx不存在
	int LOBBY_ADDFRIEND_MAXCOUNT=LOBBY_NORMAL+19;		//自身好友列表已满
	int LOBBY_ADDFRIEND_MAXCOUNT2=LOBBY_NORMAL+20;		//对方好友列表已满
	int LOBBY_ADDFRIEND_INBLACK=LOBBY_NORMAL+21;		//对方好友列表已满
	int LOBBY_DELFRIEND_NOTEXIST=LOBBY_NORMAL+22;		//不是好友

	int LOBBY_ADDBLACK_NORMAL=LOBBY_NORMAL+23;			//正常
	int LOBBY_ADDBLACK_ADDSELF=LOBBY_NORMAL+24;			//不能添加自己为黑名单
	int LOBBY_ADDBLACK_ALREADY=LOBBY_NORMAL+25;			//已经添加对方为黑名单
	int LOBBY_ADDBLACK_NOTEXIST=LOBBY_NORMAL+26;		//自己的idx或对方有idx不存在
	int LOBBY_ADDBLACK_MAXCOUNT=LOBBY_NORMAL+27;		//自身黑名单列表已满
	int LOBBY_DELBLACK_NOTEXIST=LOBBY_NORMAL+28;		//不是黑名单
///////////////////////////////////////////////////////////////
	int LOBBY_CLUB_MAXCOUNT=LOBBY_NORMAL+29;			//俱乐部满员
	int LOBBY_CREATECLUB_EXIST=LOBBY_NORMAL+30;			//被创建俱乐部已存在
	int LOBBY_DIMICLUB_NOTEXIST=LOBBY_NORMAL+31;		//被解散的俱乐部不存在

	int LOBBY_SPEAKER_BALANCE=LOBBY_NORMAL+32;			//发送喇叭余额不足

	int LOBBY_CREATEAVARAT_ERROR=LOBBY_NORMAL+33;		//创建错误
	int LOBBY_CHANGEAVARAT_NOFIND=LOBBY_NORMAL+34;		//背包中没有所要换的衣服
	int LOBBY_CHANGENICKNAME_ERR=LOBBY_NORMAL+35;		//背包中没有所要换的衣服

	int LOBBY_BUY_ERROR=LOBBY_NORMAL+36;				//购买商品出现错误
	int LOBBY_BUY_NOMONEY=LOBBY_NORMAL+37;				//金币不足
	int LOBBY_BUY_SEXERROR=LOBBY_NORMAL+38;				//性别不符
	int LOBBY_BUY_ISVIP=LOBBY_NORMAL+39;				//已有终身卡 购买vip卡时
	int LOBBY_BUY_NOSPACE=LOBBY_NORMAL+40;				//背包空间不足
	int LOBBY_BUY_ISFULL=LOBBY_NORMAL+41;				//对方已拥有该永久商品
	int LOBBY_GETPACK_ERROR=LOBBY_NORMAL+42;			//获取背包失败
	int LOBBY_DELPACK_ERROR=LOBBY_NORMAL+43;			//删除背包失败
	int LOBBY_USEPACK_ERROR=LOBBY_NORMAL+44;			//使用出现错误
	int LOBBY_TASK_STEP_OVER=LOBBY_NORMAL+45;			//已完成新手导航
	int LOBBY_TASK_STEP_ERRSTEP=LOBBY_NORMAL+46;		//非法的任务ID
	int LOBBY_TASK_STEP_ERRPRIZE=LOBBY_NORMAL+47;		//奖励返值失败（数据库错误）
	int LOBBY_KICK_BY_IDX=LOBBY_NORMAL+48;				//被禁idx
	int LOBBY_KICK_BY_NET=LOBBY_NORMAL+49;				//被禁mac
	int LOBBY_MAX=LOBBY_NORMAL+999;	

	int ROOM_NORMAL			=3000;		//正常
	int ROOM_TOKEN_ERROR=ROOM_NORMAL+1;				//token过程异常
	int ROOM_LOGIN_NONE=ROOM_NORMAL+2;				//未登录
	int ROOM_LOGIN_SUCCESS=ROOM_NORMAL+3;				//登录成功
	int ROOM_LOGIN_AGAIN=ROOM_NORMAL+4;				//重复登录
	int ROOM_LOGIN_NOUIN=ROOM_NORMAL+5;				//非法用户
	int ROOM_LOGIN_FULL=ROOM_NORMAL+6;				//房间人数满
	int ROOM_LOGIN_IFULL=ROOM_NORMAL+7;				//房间已经达到允许人数;用户身份无法登陆
	int ROOM_LOGIN_EPWD=ROOM_NORMAL+8;				//房间密码错误
	int ROOM_LOGIN_CLOSE=ROOM_NORMAL+9;				//房间关闭
	int ROOM_LOGIN_INBLACK=ROOM_NORMAL+10;				//在黑名单中
	int ROOM_LOGIN_INTBLACK=ROOM_NORMAL+11;			//在临时黑名单中
	int ROOM_LOGIN_NOTHIS=ROOM_NORMAL+12;				//房间不存在或被删除
	int ROOM_LOGIN_LOCK=ROOM_NORMAL+13;				//房间冻结
	int ROOM_LOGIN_IP_INVALIED=ROOM_NORMAL+14;			//该IP在房间内被禁
	int ROOM_ERROR_ROOMINFO=ROOM_NORMAL+15;			//接收房间信息失败
	int ROOM_ERROR_APPLYLIST=ROOM_NORMAL+16;			//接收申请列表错误
	int ROOM_ERROR_MEMLIST=ROOM_NORMAL+17;				//接收房间会员错误
	int ROOM_ERROR_UNCHAIN=ROOM_NORMAL+18;				//解除房间会员失败
	int ROOM_ERROR_PESIDEASSISTANT=ROOM_NORMAL+19;		//设置助理主持失败
	int ROOM_ERROR_PESIDE=ROOM_NORMAL+20;				//设置主持人失败
	int ROOM_ERROR_SUBHOST=ROOM_NORMAL+21;				//设置副室主失败
	int ROOM_ERROR_BLACKLIST=ROOM_NORMAL+22;			//接收黑名单失败
	int ROOM_ERROR_PASSWORD=ROOM_NORMAL+23;			//设置密码失败
	int ROOM_ERROR_INPUTFLAG=ROOM_NORMAL+24;			//设置用户进出消息失败
	int ROOM_ERROR_LOGO=ROOM_NORMAL+25;				//设置房间信息失败
	int ROOM_ERROR_ONMIC=ROOM_NORMAL+26;				//设置自由上麦失败
	int ROOM_ERROR_CHATFLAG=ROOM_NORMAL+27;			//设置允许房间公聊失败
	int ROOM_ERROR_WELCOME=ROOM_NORMAL+28;				//设置房间欢迎词失败
	int ROOM_ERROR_AFFICHE=ROOM_NORMAL+29;				//设置房间公告失败
	int ROOM_ERROR_ROOMSWITCH=ROOM_NORMAL+30;			//设置房间开启/锁定失败
	int ROOM_ERROR_ROOMNAME=ROOM_NORMAL+31;			//设置房间名失败
	int ROOM_ERROR_PARTINFO=ROOM_NORMAL+32;			//接收角色信息失败
	int ROOM_ERROR_ALREADYMEMBER=ROOM_NORMAL+33;		//已是本房间会员或是其他房间会员
	int ROOM_ERROR_MEMLISTFULL=ROOM_NORMAL+34;			//房间会员已满
	int ROOM_ERROR_ADDAGAIN=ROOM_NORMAL+35;			//房间黑名单重复添加
	int ROOM_ERROR_BLACKFULL=ROOM_NORMAL+36;			//房间黑名单已满
	int ROOM_ERROR_APPLYREFUSE=ROOM_NORMAL+37;			//服务器拒绝会员申请(申请被管理员拒绝后;24小时内不能申请)
	int ROOM_ERROR_NOTMEMBER=ROOM_NORMAL+38;			//不是房间会员
	int ROOM_ERROR_OWER2FULL=ROOM_NORMAL+39;			//副室主人数超过2人
	int ROOM_ERROR_VJFULL=ROOM_NORMAL+40;				//主持人人数超过50人
	int ROOM_ERROR_VJAFULL=ROOM_NORMAL+41;				//助理主持人数超过50人
	int ROOM_ERROR_APPLYAGAIN=ROOM_NORMAL+42;			//重复申请;请等待管理员审核
	int ROOM_ERROR_NOCHAT=ROOM_NORMAL+43;				//房间不允许公聊
	int ROOM_ERROR_FORBIDEN=ROOM_NORMAL+44;			//被禁言
	int ROOM_ERROR_APPLYFULL=ROOM_NORMAL+45;			//房间申请列表已满
	int ROOM_ERROR_GIFT_BALANCE=ROOM_NORMAL+46;		//送礼时余额不足
	int ROOM_ERROR_GIFT_UNKOWN=ROOM_NORMAL+47;			//交易金额为空
	int ROOM_ERROR_GIFT_NOTEXIST=ROOM_NORMAL+48;		//该礼物不存在
	int ROOM_ERROR_GIFT_OFFLINE=ROOM_NORMAL+49;		//礼物接收者不在房间内
	int ROOM_ERROR_MEMBER=ROOM_NORMAL+50;				//由管理员设为一般会员失败
	int ROOM_TMP_CREATE_ERROR=ROOM_NORMAL+51;			//创建练歌房失败
	int ROOM_MAX=ROOM_NORMAL+6998;

	int OPTION_TIMEOUT = 9999;		//操作超时
	int OPTION_NOTCONN=OPTION_TIMEOUT+1;				//未连接
	int OPTION_PERMISSIONS_ERROR=OPTION_TIMEOUT+2;
	int OPTION_MAX=OPTION_TIMEOUT+999;
	//}
}
