package com.jni.netutil;

/***
 * @author GLP
 */

public interface XGMessage {
	int MSG_BEGIN = 0;
	//认证连接
	int XGMSG_AUTHCON_SUCCESS = MSG_BEGIN+1;
	int XGMSG_AUTHCON_FAILED = MSG_BEGIN+2;
	int XGMSG_AUTHCON_TIMEOUT = MSG_BEGIN+3;
	int XGMSG_AUTHCON_CLOSE = MSG_BEGIN+4;
	int XGMSG_AUTHCON_ERROR = MSG_BEGIN+5;
	//认证结果
	int XGMSG_AUTHLOGIN_SUCCESS = MSG_BEGIN+6;
	int XGMSG_AUTHLOGIN_FAILED = MSG_BEGIN+7;
	
	int MSG_LOBBY_BEGIN = MSG_BEGIN+50;
	//大厅连接
	int XGMSG_LOBBYCON_SUCCESS = MSG_LOBBY_BEGIN+1;
	int XGMSG_LOBBYCON_FAILED = MSG_LOBBY_BEGIN+2;
	int XGMSG_LOBBYCON_TIMEOUT = MSG_LOBBY_BEGIN+3;
	int XGMSG_LOBBYCON_CLOSE = MSG_LOBBY_BEGIN+4;
	int XGMSG_LOBBYCON_ERROR = MSG_LOBBY_BEGIN+5;
	//大厅列表获取
	int XGMSG_LOBBYSECTION_SUCCESS = MSG_LOBBY_BEGIN+6;
	//int XGMSG_LOBBYSECTION_FAILED = MSG_LOBBY_BEGIN+7;
	//大厅登陆结果
	int XGMSG_LOBBYLOGIN_SUCCESS = MSG_LOBBY_BEGIN+8;
	int XGMSG_LOBBYLOGIN_FAILED = MSG_LOBBY_BEGIN+9;
	
	int MSG_ROOM_BEGIN = MSG_BEGIN+100;
	//房间连接
	int XGMSG_ROOMCON_SUCCESS = MSG_ROOM_BEGIN+1;
	int XGMSG_ROOMCON_FAILED= MSG_ROOM_BEGIN+2;
	int XGMSG_ROOMCON_TIMEOUT= MSG_ROOM_BEGIN+3;
	int XGMSG_ROOMCON_CLOSE= MSG_ROOM_BEGIN+4;
	int XGMSG_ROOMCON_ERROR = MSG_ROOM_BEGIN+5;
	//房间进入结果
	int XGMSG_ROOMENTER_SUCCESS = MSG_ROOM_BEGIN+6;
	int XGMSG_ROOMENTER_FAILED = MSG_ROOM_BEGIN+7;
	int XGMSG_ROOMAUTH_SUCCESS = MSG_ROOM_BEGIN+8;
	int XGMSG_ROOMAUTH_FAILED = MSG_ROOM_BEGIN+9;
	
	//聊天接收提醒
	int XGMSG_CHAT_NOTIFY = MSG_BEGIN+151;
	//礼物广播提醒
	int XGMSG_GIFT_NOTIFY = MSG_BEGIN+152;
	//喇叭广播提醒
	int XGMSG_HORN_NOTIFY = MSG_BEGIN+153;
	//中奖广播提醒
	int XGMSG_REWARD_NOTIFY = MSG_BEGIN+154;
	//在线用户列表
	int XGMSG_KTVUSER_ONLINE = MSG_BEGIN+155;
	//用户信息获取或更新的通知
	int XGMSG_USERINFO_NOTIFY = MSG_BEGIN+156;
	//用户登入大厅通知
	int XGMSG_USER_LOGIN = MSG_BEGIN+157;
	//用户登出大厅通知
	int XGMSG_USER_LOGOUT = MSG_BEGIN+158;
	//用户头像更新
	int XGMSG_USERPIC_UPDATE = MSG_BEGIN+159;
	//小喇叭发送结果
	int XGMSG_HORNRESULT_NOTIFY = MSG_BEGIN+160;
	//送礼发送结果
	int XGMSG_GIFTRESULT_NOTIFY = MSG_BEGIN+161;
	//更新用户金币信息
	int XGMSG_USERGOLD_UPDATE = MSG_BEGIN+162;
	//包厢状态改变
	int XGMSG_ROOMSTAT_UPDATE = MSG_BEGIN+163;
	//歌曲正常结束
	int XGMSG_NORMAL_SONGEND = MSG_BEGIN+164;
	//本地礼物数据库完成
	int XGMSG_GIFTDATA_FINISHED = MSG_BEGIN+165;
	//ktv 包厢当前的点歌列表
	int XGMSG_CUR_SONGLIST = MSG_BEGIN+166;
	//获取到喇叭发送者的用户信息
	int XGMSG_USERINFO_FORHORN = MSG_BEGIN+167;
	//用户昵称更新
	int XGMSG_USERNAME_UPDATE = MSG_BEGIN+168;
	//踢用户出大厅
	int XGMSG_FORCEOUT_LOBBY = MSG_BEGIN+169;
	//通知
	int XGMSG_NOTIFY_MESSAGE = MSG_BEGIN+170;
	//红包发送结果返回
	int XGMSG_HONGBAO_SENDRESULT = MSG_BEGIN+171;
	//收到红包
	int XGMSG_HONGBAO_RECV = MSG_BEGIN+172;
	//抢红包结果返回
	int XGMSG_HONGBAO_VIERESULT = MSG_BEGIN+173;
	//红包领取详情
	int XGMSG_HONGBAO_DETAIL = MSG_BEGIN+174;
	//通知最近演唱的歌曲
	int XGMSG_SINGSONG_RECENT = MSG_BEGIN+175;
	//通知红包可领取的数量，用于首页的红点显示
	int XGMSG_HONGBAO_CANGET = MSG_BEGIN+176;
	//红包的状态查询结果返回
	int XGMSG_HONGBAO_STATUS=MSG_BEGIN+177;
	//包厢红包查询结果返回
	int XGMSG_HONGBAO_ROOM=MSG_BEGIN+178;
}
